---
- name: Install Git, Docker, and Docker Compose 
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: yes

    - name: Add Docker repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes

    - name: Update apt repository after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3

    - name: Install setuptools_rust
      pip:
        name: setuptools-rust
        executable: pip3

    - name: Install Docker Compose
      become: yes
      block:
        - name: Create Docker CLI plugins directory
          file:
            path: ~/.docker/cli-plugins/
            state: directory

        - name: Download Docker Compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64"
            dest: "~/.docker/cli-plugins/docker-compose"
            mode: '0755'

        - name: Verify Docker Compose installation
          command: docker compose version